// @generated by scripts/runtime/generate_app_metadata.py; do not edit by hand.
use super::{AppLaunchEnv, AppRuntimeMetadata, ManifestAppLaunch};

pub const COUNTER_MANIFEST_RUNTIME: AppRuntimeMetadata = AppRuntimeMetadata {
    bundle_env: "SHADOW_RUNTIME_APP_COUNTER_BUNDLE_PATH",
    input_path: "runtime/app-counter/app.tsx",
    cache_dir: "build/runtime/app-counter-host",
};

pub const COUNTER_MANIFEST_LAUNCH: ManifestAppLaunch = ManifestAppLaunch::TypeScript {
    runtime: COUNTER_MANIFEST_RUNTIME,
    launch_env: &[],
};

pub const CAMERA_MANIFEST_RUNTIME: AppRuntimeMetadata = AppRuntimeMetadata {
    bundle_env: "SHADOW_RUNTIME_APP_CAMERA_BUNDLE_PATH",
    input_path: "runtime/app-camera/app.tsx",
    cache_dir: "build/runtime/app-camera-host",
};

pub const CAMERA_MANIFEST_LAUNCH: ManifestAppLaunch = ManifestAppLaunch::TypeScript {
    runtime: CAMERA_MANIFEST_RUNTIME,
    launch_env: &[],
};

pub const TIMELINE_MANIFEST_RUNTIME: AppRuntimeMetadata = AppRuntimeMetadata {
    bundle_env: "SHADOW_RUNTIME_APP_TIMELINE_BUNDLE_PATH",
    input_path: "runtime/app-nostr-timeline/app.tsx",
    cache_dir: "build/runtime/app-nostr-timeline-host",
};

pub const TIMELINE_MANIFEST_LAUNCH: ManifestAppLaunch = ManifestAppLaunch::TypeScript {
    runtime: TIMELINE_MANIFEST_RUNTIME,
    launch_env: &[],
};

pub const PODCAST_MANIFEST_RUNTIME: AppRuntimeMetadata = AppRuntimeMetadata {
    bundle_env: "SHADOW_RUNTIME_APP_PODCAST_BUNDLE_PATH",
    input_path: "runtime/app-podcast-player/app.tsx",
    cache_dir: "build/runtime/app-podcast-player-host",
};

pub const PODCAST_MANIFEST_LAUNCH: ManifestAppLaunch = ManifestAppLaunch::TypeScript {
    runtime: PODCAST_MANIFEST_RUNTIME,
    launch_env: &[],
};

pub const CASHU_MANIFEST_RUNTIME: AppRuntimeMetadata = AppRuntimeMetadata {
    bundle_env: "SHADOW_RUNTIME_APP_CASHU_BUNDLE_PATH",
    input_path: "runtime/app-cashu-wallet/app.tsx",
    cache_dir: "build/runtime/app-cashu-wallet-host",
};

pub const CASHU_MANIFEST_LAUNCH: ManifestAppLaunch = ManifestAppLaunch::TypeScript {
    runtime: CASHU_MANIFEST_RUNTIME,
    launch_env: &[],
};

pub const RUST_DEMO_LAUNCH_ENV: [AppLaunchEnv; 1] = [("SHADOW_RUNTIME_CAMERA_ALLOW_MOCK", "1")];

pub const RUST_DEMO_MANIFEST_LAUNCH: ManifestAppLaunch = ManifestAppLaunch::Rust {
    launch_env: &RUST_DEMO_LAUNCH_ENV,
};

pub const RUST_TIMELINE_LAUNCH_ENV: [AppLaunchEnv; 3] = [
    ("SHADOW_RUST_TIMELINE_LIMIT", "18"),
    (
        "SHADOW_RUST_TIMELINE_RELAY_URLS",
        "wss://relay.primal.net/,wss://relay.damus.io/",
    ),
    ("SHADOW_RUST_TIMELINE_SYNC_ON_START", "1"),
];

pub const RUST_TIMELINE_MANIFEST_LAUNCH: ManifestAppLaunch = ManifestAppLaunch::Rust {
    launch_env: &RUST_TIMELINE_LAUNCH_ENV,
};
