// @generated by scripts/runtime/generate_app_metadata.py; do not edit by hand.
use super::{AppId, DemoApp};
use crate::color::{ICON_CYAN, ICON_GREEN, ICON_ORANGE, ICON_PINK};

pub const SHELL_APP_ID: AppId = AppId::new("shell");
pub const SHELL_WAYLAND_APP_ID: &str = "dev.shadow.shell";

pub const COUNTER_APP_ID: AppId = AppId::new("counter");
pub const COUNTER_WAYLAND_APP_ID: &str = "dev.shadow.counter";
pub const COUNTER_WINDOW_TITLE: &str = "Shadow Counter";
pub const COUNTER_RUNTIME_BUNDLE_ENV: &str = "SHADOW_RUNTIME_APP_COUNTER_BUNDLE_PATH";
pub const COUNTER_RUNTIME_INPUT_PATH: &str = "runtime/app-counter/app.tsx";
pub const COUNTER_RUNTIME_CACHE_DIR: &str = "build/runtime/app-counter-host";

pub const COUNTER_APP: DemoApp = DemoApp {
    id: COUNTER_APP_ID,
    icon_label: "01",
    title: "Counter",
    subtitle: "Counter demo",
    lifecycle_hint: "Shelving keeps the live counter warm until the app exits.",
    binary_name: "shadow-blitz-demo",
    wayland_app_id: COUNTER_WAYLAND_APP_ID,
    window_title: COUNTER_WINDOW_TITLE,
    runtime_bundle_env: COUNTER_RUNTIME_BUNDLE_ENV,
    runtime_input_path: COUNTER_RUNTIME_INPUT_PATH,
    runtime_cache_dir: COUNTER_RUNTIME_CACHE_DIR,
    icon_color: ICON_CYAN,
};

pub const CAMERA_APP_ID: AppId = AppId::new("camera");
pub const CAMERA_WAYLAND_APP_ID: &str = "dev.shadow.camera";
pub const CAMERA_WINDOW_TITLE: &str = "Shadow Camera";
pub const CAMERA_RUNTIME_BUNDLE_ENV: &str = "SHADOW_RUNTIME_APP_CAMERA_BUNDLE_PATH";
pub const CAMERA_RUNTIME_INPUT_PATH: &str = "runtime/app-camera/app.tsx";
pub const CAMERA_RUNTIME_CACHE_DIR: &str = "build/runtime/app-camera-host";

pub const CAMERA_APP: DemoApp = DemoApp {
    id: CAMERA_APP_ID,
    icon_label: "CM",
    title: "Camera",
    subtitle: "Take and review a photo",
    lifecycle_hint: "The latest captured frame stays visible while the app remains warm.",
    binary_name: "shadow-blitz-demo",
    wayland_app_id: CAMERA_WAYLAND_APP_ID,
    window_title: CAMERA_WINDOW_TITLE,
    runtime_bundle_env: CAMERA_RUNTIME_BUNDLE_ENV,
    runtime_input_path: CAMERA_RUNTIME_INPUT_PATH,
    runtime_cache_dir: CAMERA_RUNTIME_CACHE_DIR,
    icon_color: ICON_ORANGE,
};

pub const TIMELINE_APP_ID: AppId = AppId::new("timeline");
pub const TIMELINE_WAYLAND_APP_ID: &str = "dev.shadow.timeline";
pub const TIMELINE_WINDOW_TITLE: &str = "Shadow Timeline";
pub const TIMELINE_RUNTIME_BUNDLE_ENV: &str = "SHADOW_RUNTIME_APP_TIMELINE_BUNDLE_PATH";
pub const TIMELINE_RUNTIME_INPUT_PATH: &str = "runtime/app-nostr-timeline/app.tsx";
pub const TIMELINE_RUNTIME_CACHE_DIR: &str = "build/runtime/app-nostr-timeline-host";

pub const TIMELINE_APP: DemoApp = DemoApp {
    id: TIMELINE_APP_ID,
    icon_label: "TL",
    title: "Timeline",
    subtitle: "Local Nostr cache",
    lifecycle_hint: "Shelving keeps the live draft warm. Full restart reloads cached notes.",
    binary_name: "shadow-blitz-demo",
    wayland_app_id: TIMELINE_WAYLAND_APP_ID,
    window_title: TIMELINE_WINDOW_TITLE,
    runtime_bundle_env: TIMELINE_RUNTIME_BUNDLE_ENV,
    runtime_input_path: TIMELINE_RUNTIME_INPUT_PATH,
    runtime_cache_dir: TIMELINE_RUNTIME_CACHE_DIR,
    icon_color: ICON_ORANGE,
};

pub const PODCAST_APP_ID: AppId = AppId::new("podcast");
pub const PODCAST_WAYLAND_APP_ID: &str = "dev.shadow.podcast";
pub const PODCAST_WINDOW_TITLE: &str = "No Solutions Player";
pub const PODCAST_RUNTIME_BUNDLE_ENV: &str = "SHADOW_RUNTIME_APP_PODCAST_BUNDLE_PATH";
pub const PODCAST_RUNTIME_INPUT_PATH: &str = "runtime/app-podcast-player/app.tsx";
pub const PODCAST_RUNTIME_CACHE_DIR: &str = "build/runtime/app-podcast-player-host";

pub const PODCAST_APP: DemoApp = DemoApp {
    id: PODCAST_APP_ID,
    icon_label: "NS",
    title: "Podcast",
    subtitle: "No Solutions",
    lifecycle_hint: "Shelving keeps the current episode loaded until the player is released.",
    binary_name: "shadow-blitz-demo",
    wayland_app_id: PODCAST_WAYLAND_APP_ID,
    window_title: PODCAST_WINDOW_TITLE,
    runtime_bundle_env: PODCAST_RUNTIME_BUNDLE_ENV,
    runtime_input_path: PODCAST_RUNTIME_INPUT_PATH,
    runtime_cache_dir: PODCAST_RUNTIME_CACHE_DIR,
    icon_color: ICON_PINK,
};

pub const CASHU_APP_ID: AppId = AppId::new("cashu");
pub const CASHU_WAYLAND_APP_ID: &str = "dev.shadow.cashu";
pub const CASHU_WINDOW_TITLE: &str = "Shadow Cashu";
pub const CASHU_RUNTIME_BUNDLE_ENV: &str = "SHADOW_RUNTIME_APP_CASHU_BUNDLE_PATH";
pub const CASHU_RUNTIME_INPUT_PATH: &str = "runtime/app-cashu-wallet/app.tsx";
pub const CASHU_RUNTIME_CACHE_DIR: &str = "build/runtime/app-cashu-wallet-host";

pub const CASHU_APP: DemoApp = DemoApp {
    id: CASHU_APP_ID,
    icon_label: "CU",
    title: "Cashu",
    subtitle: "Wallet + Lightning",
    lifecycle_hint: "Shelving keeps your trusted mints and draft flows one tap away.",
    binary_name: "shadow-blitz-demo",
    wayland_app_id: CASHU_WAYLAND_APP_ID,
    window_title: CASHU_WINDOW_TITLE,
    runtime_bundle_env: CASHU_RUNTIME_BUNDLE_ENV,
    runtime_input_path: CASHU_RUNTIME_INPUT_PATH,
    runtime_cache_dir: CASHU_RUNTIME_CACHE_DIR,
    icon_color: ICON_GREEN,
};

pub const DEMO_APPS: [DemoApp; 5] = [
    COUNTER_APP,
    CAMERA_APP,
    TIMELINE_APP,
    PODCAST_APP,
    CASHU_APP,
];

pub const VM_SHELL_DEMO_APPS: [DemoApp; 5] = [
    COUNTER_APP,
    CAMERA_APP,
    TIMELINE_APP,
    PODCAST_APP,
    CASHU_APP,
];

pub const PIXEL_SHELL_DEMO_APPS: [DemoApp; 5] = [
    COUNTER_APP,
    CAMERA_APP,
    TIMELINE_APP,
    PODCAST_APP,
    CASHU_APP,
];
